#!/bin/sh

add_todo() {
    read -ep "What is the name of the art you want to eventually consume? " entry_name
    read -ep "Creator? " creator 
    echo "- $entry_name by $creator" | fold -w57 -s >> ../site/$2/todo.txt
}

die() {
    printf 'error: %s.\n' "$1" >&2
    exit 1
}

main() {
    genre_name="$1"
    genre_folder=$(printf '%s' "${genre_name,,}" | tr ' ' '_')
    [ ! -d ../site/"$genre_folder" ] || [ -z "$genre_name" ] && die "genre doesn't exist"
    add_todo "$genre_name" "$genre_folder"
    cd ../
    ./make
}

main "$@"
