#!/bin/sh

add_dir() {
    dirname=$(printf '%s\n' "${1,,}")
    mkdir -p ../site/"$dirname"
}

add_file() {
    fname=$(printf '%s\n' "${1,,}")
    title=$(printf '%s\n' "${2^^}")
    echo $title > /tmp/$fname
    ./format_box /tmp/$fname > ../site/"$fname".txt
    echo "" >> ../site/"$fname".txt
}

add_link() {
    fname=$(printf '%s\n' "${1,,}")
    sed -r "s:(<!--%%GENRES%%-->):\1 <a href=/art-manager/$fname>$2</a> :g" ../template.html > ./template.html2
    mv ./template.html2 ../template.html
}

add_todo() {
    fname=$(printf '%s\n' "${1,,}")
    title=$(printf 'TODO: %s\n' "${2^^}")
    echo $title > /tmp/$fname
    ./format_box /tmp/$fname > ../site/"$fname"/todo.txt
    echo "" >> ../site/"$fname"/todo.txt
}

main() {
    NAME="$1"
    NAME_with="$(echo "$NAME" | tr ' ' '_')"
    add_dir "$NAME_with"
    add_file "$NAME_with" "$NAME"
    add_link "$NAME_with" "$NAME"
    add_todo "$NAME_with" "$NAME"
    cd ../
    ./make
}

main "$@"
